services:
  ros1_bridge:
    build:
      context: ./bridge
      network: host
    cap_add:
      - NET_ADMIN
    command:
      - /bin/bash
      - -c
      - |
        unset ROS_DISTRO
        source /opt/ros/noetic/setup.bash
        export ROS_MASTER_URI=http://10.68.0.1:11311
        unset ROS_DISTRO
        source /opt/ros/foxy/setup.bash
        source /bridge_ws/install/setup.bash
        exec ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
    networks:
      field_net:
        ipv4_address: 10.68.0.52
    environment:
      - ROS_MASTER_URI=http://10.68.0.1:11311
      - ROS_IP=10.68.0.52
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

  ros2_app:
    build:
      context: ./ros2_app
      network: host
    container_name: ros2_app

    volumes:
      - ./ros2_app:/ros2_ws/src/image_listener

    working_dir: /ros2_ws
    restart: unless-stopped

    command: >
      bash -c "
      source /opt/ros/foxy/setup.bash &&
      source install/setup.bash || true &&
      ros2 run image_listener image_subscriber
      "

  steamvr:
    build:
      context: ./steamvr
      network: host

    container_name: steamvr
    privileged: true
    restart: no

    environment:
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp/runtime-steam

      # NVIDIA
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute,display
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json

      # OpenXR / Monado
      - XRT_RUNTIME_JSON=/usr/local/share/openxr/1/openxr_monado.json
      - XRT_COMPOSITOR_FORCE_XCB=1
      - XRT_DEBUG_GUI=0

      # tuning
      - MESA_GLTHREAD=true
      - vblank_mode=0

    volumes:
      # X11 passthrough
      - /tmp/.X11-unix:/tmp/.X11-unix

      # system / hardware
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /run/udev:/run/udev
      - /run/dbus:/run/dbus
      - /sys:/sys

      # Monado state
      - monado_config:/home/steam/.config/monado
      - monado_logs:/home/steam/.local/share/monado

    devices:
      - /dev/dri:/dev/dri

    runtime: nvidia

    networks:
      field_net:
        ipv4_address: 10.68.0.53

    ports:
      - "5900:5900"

volumes:
  monado_config:
  monado_logs:

networks:
  field_net:
    driver: macvlan
    driver_opts:
      parent: ${NIC:-enp2s0f0}
    ipam:
      config:
        - subnet: 10.68.0.0/24
          gateway: 10.68.0.1