<?xml version="1.0"?>
<package format="3">
  <name>vive_moveit_server</name>
  <version>0.1.0</version>
  <description>ROS 2 MoveIt teleoperation server for Vive WebRTC input.</description>

  <maintainer email="mateuszwatly@gmail.com">Mateusz Wątły</maintainer>
  <license>Apache-2.0</license>
  <url type="repository">https://github.com/ichores-research/vive_teleop</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_servo</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>trajectory_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>tiago_description</exec_depend>
  <exec_depend>tiago_moveit_config</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
